baseURL = "/"
author = "Apache Nutch Project Management Committee"
languageCode = "en-us"
title = "Apache Nutch™"
theme = "kube"
themesDir = "themes"
description = "Apache Nutch is a highly extensible, highly scalable, matured, production-ready Web crawler. Nutch enables fine grained configuration, relying on Apache Hadoop™ data structures, which are great for batch processing."
Paginate = 4

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown content

[Params]
  siteBaseURL = "https://nutch.apache.org"
  RSSLink = "/index.xml"
  author = "Apache Nutch Project Management Committee"
  github = "https://github.com/apache/nutch"
  twitter = "@ApacheNutch"
  email = "dev@nutch.apache.org"

[[menu.main]]
    name = "Community"
    weight = -100
    url = "/community/"
[[menu.main]]
    name = "Development"
    weight = -100
    url = "/development/"
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/documentation/"
[[menu.main]]
    name = "Download"
    weight = -100
    url = "/download/"    
[[menu.main]]
    name = "News"
    weight = -100
    url = "/news/"
[[menu.main]]
    name = "Apache"
    weight = -100
    url = "/apache/"

